server {
    listen 80;
    listen [::]:80;
    server_name assecce.com.br www.assecce.com.br;

    root /usr/share/nginx/html;
    index index.html;

    # Certbot - emissão de certificado SSL
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Página em construção
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bloqueia arquivos sensíveis
    location ~* \.(env|git|sh|sql|log)$ {
        deny all;
        return 404;
    }
}
